export const config = { runtime: 'edge' };

// Reports may only be delivered to addresses on this corporate domain. This is the
// authoritative check — the client performs the same validation for UX, but it is
// bypassable, so every request is re-validated here. Keep in sync with
// ALLOWED_EMAIL_DOMAIN in src/main.ts.
const ALLOWED_EMAIL_DOMAIN = 'amundi.com';

function isAllowedEmail(email: string): boolean {
  return email.trim().toLowerCase().endsWith(`@${ALLOWED_EMAIL_DOMAIN}`);
}

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405 });
  }

  let body: {
    to: string;
    name: string;
    tripName: string;
    pdfBase64: string;
    xlsxBase64?: string;
    pdfAttachments?: { filename: string; base64: string }[];
  };

  try {
    body = await req.json() as typeof body;
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON body' }), { status: 400 });
  }

  const { to, name, tripName, pdfBase64, xlsxBase64, pdfAttachments = [] } = body;

  if (!to || !name || !tripName || !pdfBase64) {
    return new Response(JSON.stringify({ error: 'Missing required fields' }), { status: 400 });
  }

  if (!isAllowedEmail(to)) {
    return new Response(
      JSON.stringify({ error: `Reports may only be sent to @${ALLOWED_EMAIL_DOMAIN} addresses` }),
      { status: 403 },
    );
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return new Response(JSON.stringify({ error: 'RESEND_API_KEY not configured' }), { status: 500 });
  }

  const date     = new Date().toLocaleDateString('en-IE', { day: '2-digit', month: 'short', year: 'numeric' });
  const safeTrip = tripName.replace(/[^a-z0-9]/gi, '_');

  const pdfNote = pdfAttachments.length > 0
    ? `<p>Additionally, <strong>${pdfAttachments.length} PDF document${pdfAttachments.length > 1 ? 's' : ''}</strong> (e.g. airline bookings) are attached.</p>`
    : '';

  const attachments = [
    { filename: `${safeTrip}_expense_report.pdf`, content: pdfBase64 },
    ...(xlsxBase64 ? [{ filename: `${safeTrip}_expense_form.xlsx`, content: xlsxBase64 }] : []),
    ...pdfAttachments.map(a => ({ filename: a.filename, content: a.base64 })),
  ];

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type':  'application/json',
      },
      body: JSON.stringify({
        from:        'Expense Tracker <expenses@ajagbudi.com>',
        to:          [to],
        subject:     `[${tripName}] Expense Report — ${name} — ${date}`,
        html: `
          <div style="font-family:sans-serif;color:#1a202c;max-width:600px;margin:0 auto">
            <h2 style="color:#1d4ed8">Expense Report: ${tripName}</h2>
            <p>Hi ${name.split(' ')[0]},</p>
            <p>Please find attached your expense report for <strong>${tripName}</strong>.</p>
            <p>The <strong>PDF</strong> contains all receipt images and a summary table.</p>
            <p>The <strong>Excel file</strong> (${safeTrip}_expense_form.xlsx) is the completed expense form ready to submit — open it in Excel, sign the declaration, and forward to your approver.</p>
            ${pdfNote}
            <hr style="border:1px solid #e2e8f0;margin:24px 0"/>
            <p style="color:#718096;font-size:12px">Generated by Expense Tracker PWA</p>
          </div>`,
        attachments,
      }),
    });

    const data = await res.json() as { id?: string; name?: string; message?: string };

    if (!res.ok) {
      return new Response(
        JSON.stringify({ error: data.message ?? data.name ?? `Resend error ${res.status}` }),
        { status: 502 },
      );
    }

    return new Response(JSON.stringify({ ok: true }), { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), { status: 500 });
  }
}
