import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export const config = { runtime: 'edge' };

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405 });
  }

  let body: {
    to: string;
    name: string;
    tripName: string;
    pdfBase64: string;
    csv: string;
    pdfAttachments?: { filename: string; base64: string }[];
  };

  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400 });
  }

  const { to, name, tripName, pdfBase64, csv, pdfAttachments = [] } = body;

  if (!to || !name || !tripName || !pdfBase64 || !csv) {
    return new Response(JSON.stringify({ error: 'Missing required fields' }), { status: 400 });
  }

  const date     = new Date().toLocaleDateString('en-IE', { day: '2-digit', month: 'short', year: 'numeric' });
  const safeTrip = tripName.replace(/[^a-z0-9]/gi, '_');

  const pdfNote = pdfAttachments.length > 0
    ? `<p>Additionally, <strong>${pdfAttachments.length} PDF document${pdfAttachments.length > 1 ? 's' : ''}</strong> (e.g. airline bookings) are attached separately.</p>`
    : '';

  try {
    await resend.emails.send({
      from:    'Expense Tracker <expenses@resend.dev>',
      to:      [to],
      subject: `[${tripName}] Expense Report — ${name} — ${date}`,
      html: `
        <div style="font-family:sans-serif;color:#1a202c;max-width:600px;margin:0 auto">
          <h2 style="color:#1d4ed8">Expense Report: ${tripName}</h2>
          <p>Hi ${name.split(' ')[0]},</p>
          <p>Please find attached your expense report for <strong>${tripName}</strong>.</p>
          <p>The PDF contains all receipt images and a summary table. The CSV summary below can be pasted directly into the expenses spreadsheet.</p>
          ${pdfNote}
          <hr style="border:1px solid #e2e8f0;margin:24px 0"/>
          <h3 style="color:#374151">CSV Summary</h3>
          <pre style="background:#f7fafc;padding:16px;border-radius:8px;font-size:12px;overflow-x:auto;white-space:pre-wrap">${csv}</pre>
          <hr style="border:1px solid #e2e8f0;margin:24px 0"/>
          <p style="color:#718096;font-size:12px">Generated by Expense Tracker PWA</p>
        </div>`,
      attachments: [
        {
          filename:    `${safeTrip}_expense_report.pdf`,
          content:     pdfBase64,
          contentType: 'application/pdf',
        },
        ...pdfAttachments.map(a => ({
          filename:    a.filename,
          content:     a.base64,
          contentType: 'application/pdf',
        })),
      ],
    });

    return new Response(JSON.stringify({ ok: true }), { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), { status: 500 });
  }
}
